# Data parameters
data_source: sim
n: 200000
learning_rate: 0.01
n_estimators_max: 10000
min_samples_split: 10
min_samples_leaf: 10
max_depth: 2

# Tuning parameters
n_splits: 2
random_state: 14
parallel: true
n_jobs: -1
