n: 2000
p: 3
random_state: 11
correlations:

distribution: "normal"
z0: 0
beta_functions:
  - "2 * np.ones(len(X))"
  - "np.zeros(len(X))"
  - "np.zeros(len(X))"

learning_rate: 0.1
n_estimators_max: 100
min_samples_split: 2
min_samples_leaf: 20
max_depth: 2
glm_init: true

test_size: 0.5
n_splits: 2