n: 10000
feature_list:
  - VehPower
  - VehAge
  - DrivAge
  - BonusMalus
  - Density
random_state: 11
target: ClaimNb
weights: Exposure

distribution: poisson

learning_rate: 0.001
n_estimators_max: 100
min_samples_split: 30
min_samples_leaf: 25
max_depth: 2
glm_init: true
features: null

test_size: 0.2
n_splits: 2
parallel: false
n_jobs: -1
stratified: true