data_source: simulation

n: 200000
learning_rate: 0.01
n_estimators_max: 10
min_samples_split: 10
min_samples_leaf: 10
max_depth: 2
glm_init: true
feature_selection: null

n_splits: 2
random_state: 14
parallel: true
n_jobs: -1
