n: 20000
p: 3
random_state: 11
correlations:

distribution: "normal"
z0: 0
beta_functions:
  - "0.5 * np.ones(len(X))"
  - "-0.25 * X[:, 1]"
  - "0.5 * np.abs(X[:, 2]) * np.sin(2 * X[:, 2]) / X[:, 2]"

learning_rate: 0.1
n_estimators_max: 100
min_samples_split: 2
min_samples_leaf: 20
max_depth: 2
glm_init: true

test_size: 0.5
n_splits: 2